### ISSUE TITLE
Access denied when extracting datasets

### ISSUE THREAD

**Issue by PenguinGabe** [openai/glow#1]
`curl https://storage.googleapis.com/glow-demo/celeb-tfr.tar`

Got the following permissions error:

```
<Error>
<Code>AccessDenied</Code>
<Message>Access denied.</Message>
<Details>
Anonymous caller does not have storage.objects.get access to glow-demo/celeb-tfr.tar.
</Details>
</Error>
```

**Comment by prafullasd** [comment]
Fixed links, try now?

**Comment by PenguinGabe** [comment]
`celeba` is working, but `lsun` is broken, as @edrickwong mentioned above

**Comment by prafullasd** [comment]
Lsun is still uploading, should be up by tomorrow!

**Comment by thealgebraist** [comment]
Also, I think you mean:

`wget https://storage.googleapis.com/glow-demo/celeb-tfr.tar
`

since curl just writes the tar to stdout (on OSX at least).

**Comment by thetna** [comment]
I am facing the same error for CelebA too.

  ***?xml` version='1.0' encoding='UTF-8'?><Error><Code>AccessDenied</Code><Message>Access denied..... ***

**Comment by thetna** [comment]
Still the same error for CelebA as well
`  <?xml version='1.0' encoding='UTF-8'?><Error><Code>AccessDenied</Code><Message>Access denied. `

**Comment by prafullasd** [comment]
LSUN should be working now too. Note that the link by @PenguinGabe is based on the old README. README has been fixed now, use the links from the new README, listed here
`https://storage.googleapis.com/glow-demo/data/celeba-tfr.tar`
`https://storage.googleapis.com/glow-demo/data/imagenet-oord-tfr.tar`
`https://storage.googleapis.com/glow-demo/data/imagenet-tfr.tar`
`https://storage.googleapis.com/glow-demo/data/lsun-tfr.tar`
`https://storage.googleapis.com/glow-demo/data/lsun_realnvp-tfr.tar`

@thealgebraist Yep, I should've put `> celeba-tfr.tar` after the curl, replaced with `wget` now
