### ISSUE TITLE
Syntax Error

### ISSUE THREAD

**Issue by 123Abelian** [openai/glow#19]
When I use the following command on the Cifar10 python-oriented dataset: 

mpiexec -n 1 python train.py --problem cifar10 --image_size 32 --n_level 3 --depth 32 --flow_permutation 2 --flow_coupling 0 --seed 0 --learntop --lr 0.001 --n_bits_x 5 --ycond --weight_y=0.01

I just get the following error:

File "train.py", line 23
    print(*args, **kwargs)
          ^
SyntaxError: invalid syntax
-------------------------------------------------------
Primary job  terminated normally, but 1 process returned
a non-zero exit code. Per user-direction, the job has been aborted.
-------------------------------------------------------
--------------------------------------------------------------------------
mpiexec detected that one or more processes exited with non-zero status, thus causing
the job to be terminated. The first process to do so was:

  Process name: [[25954,1],0]
  Exit code:    1
--------------------------------------------------------------------------

Any ideas as to what could be happening? I've not modified the code in any way, shape, or form.

**Comment by 123Abelian** [comment]
Never mind, set python to python3 and it worked

**Comment by ascenoputing** [comment]
I am using python3.7, the error still exist
