### ISSUE TITLE
Error occured while getting the pretrain model

### ISSUE THREAD

**Issue by tangji08** [openai/glow#25]
Warning: wildcards not supported in HTTP.
--2018-07-23 14:37:42--  https://storage.googleapis.com/glow-demo/logs/lsun-rnvp-[bdr/crh/twr].tar
Resolving storage.googleapis.com... 216.58.201.240
Connecting to storage.googleapis.com|216.58.201.240|:443... connected.
HTTP request sent, awaiting response... 403 Forbidden
2018-07-23 14:37:43 ERROR 403: Forbidden.

**Comment by indolant** [comment]
https://storage.googleapis.com/glow-demo/logs/lsun-rnvp-twr.tar
