### ISSUE TITLE
Any plan to make a pytorch version in the future?

### ISSUE THREAD

**Issue by engharat** [openai/glow#3]
Hi,
I've just read your paper and I'm impressed by the good results that you got, especially for a non adversarial model.
Have you planned to make a pytorch porting in the next weeks?
I imagine several things that you implemented are not still available on pytorch, so doing the porting myself would not be an easy task.

**Comment by prafullasd** [comment]
Thanks @engharat. We have no current plans of making a pytorch port, though would be great to see one from the community!

**Comment by Amir-Arsalan** [comment]
@engharat What things are not available in PyTorch? Isn't it the main missing thing 1x1 invertible convolutions?

**Comment by pclucas14** [comment]
Everything seems to be available in pytorch. The LU decomposition might be slower, but other operations should all be available.
