### ISSUE TITLE
load graph_optimized.pb error no EdgeBias

### ISSUE THREAD

**Issue by Jack-Cherish** [openai/glow#31]
I pip install the blocksparse. But there is also error:
    raise ValueError('No op named %s in defined operations.' % node.op)
ValueError: No op named EdgeBias in defined operations.

**Comment by victorherbemontagne** [comment]
Same problem here, 
@Jack-Cherish are you running on CPU or GPU?

**Comment by prafullasd** [comment]
Did it pip install without errors / can you share the console output when you pip installed? What tensorflow version are you using? It needs the glu version, and at least 1.8.0
Until then, check #28 on how to skip blocksparse and use unoptimized model.

**Comment by Jack-Cherish** [comment]
@victorherbemontagne GPU
@prafullasd I install tensorflow-gpu 1.4.0.
I try it on tensorflow-gpu 1.8.0 once more.
