### ISSUE TITLE
how to use demo/align_image.py?

### ISSUE THREAD

**Issue by DeHysolate** [openai/glow#33]
OLD USAGE
python align_faces.py --shape-predictor shape_predictor_68_face_landmarks.dat --image images/example_01.jpg

It is useless

**Comment by prafullasd** [comment]
Import it and use the `align` or `align_face` functions. The comments above their definition describe their usage.

**Comment by EricGzq** [comment]
> OLD USAGE
> python align_faces.py --shape-predictor shape_predictor_68_face_landmarks.dat --image images/example_01.jpg
> 
> It is useless

Hi, did you success in `align_face.py`? I got a picture that changed color, just like Avatar.
![img2](https://user-images.githubusercontent.com/43031210/49360284-b5b86500-f713-11e8-9041-37fed1601b49.png)
