### ISSUE TITLE
Typo in the source code

### ISSUE THREAD

**Issue by chenzhekl** [openai/glow#45]
It seems  

`if arg_scope([get_variable_ddi], trainable=trainable):`

should be 

`with arg_scope([get_variable_ddi], trainable=trainable):`

https://github.com/openai/glow/blob/654ddd0ddd976526824455074aa1eaaa92d095d8/tfops.py#L72

**Comment by dpkingma** [comment]
@chenzhekl That's indeed a typo.
It doesn't affect the experiments; we never use trainable=False, and it's True by default.
