### ISSUE TITLE
Op type not registered "Edge Bias" in binary running on ...

### ISSUE THREAD

**Issue by LutetiumX** [openai/glow#47]
**System**:
Ubuntu 16.04
Anaconda Python 3.6
Tensorflow 1.8.0 built from source
GPU Compute Capability 5.0
Cuda 9.2, CuDNN 7.1

After installed the required libraries, I tried on of the demos with:
```
python videos.py 
```
in demo.

This is the traceback.

```
Traceback (most recent call last):
  File "videos.py", line 1, in <module>
    from model import encode, manipulate_range, mix_range
  File "/home/karen/workspace/blog/glow/glow/demo/model.py", line 88, in <module>
    tf.import_graph_def(graph_def_optimized)
  File "/home/karen/anaconda3/envs/glow/lib/python3.6/site-packages/tensorflow/python/util/deprecation.py", line 432, in new_func
    return func(*args, **kwargs)
  File "/home/karen/anaconda3/envs/glow/lib/python3.6/site-packages/tensorflow/python/framework/importer.py", line 489, in import_graph_def
    graph._c_graph, serialized, options)  # pylint: disable=protected-access
tensorflow.python.framework.errors_impl.NotFoundError: Op type not registered 'EdgeBias' in binary running on
```

**Comment by seansaito** [comment]
I also get the error when running `python models.py` in `demo`. Running on Python 3.5.2, TF 1.8.0 and CUDA 9.0

**Comment by wangzhe3224** [comment]
the same to me. TF 1.8.0 without gpu

**Comment by seansaito** [comment]
I was able to resolve this by installing the correct blocksparse library found here: https://github.com/openai/glow/blob/654ddd0ddd976526824455074aa1eaaa92d095d8/demo/script.sh#L20

**Comment by pauluskim** [comment]
# If blocksparse doesn't install, use unoptimized model (and set optimized=False in model.py)
# curl https://storage.googleapis.com/glow-demo/large3/graph_unoptimized.pb > graph_unoptimized.pb

Did you try this?
download the pb and then set the "optimized" variable in model.py False?

**Comment by LutetiumX** [comment]
Solved with @pauluskim comment and @seansaito's comment.
