### ISSUE TITLE
Datasets are all too big

### ISSUE THREAD

**Issue by jinfagang** [openai/glow#6]
The dataset all about 100G+, hard to test and downloaded, is there any tiny test datasets?

**Comment by prafullasd** [comment]
For small scale testing, use CIFAR10/MNIST. They dont need to be downloaded separately, just run train.py with --problem cifar10/mnist, keras will automatically download them. 
For slightly larger scale, you can use Imagenet 64x64, thats 20Gb. I can upload a 256x256 downsampled CelebA-HQ soon, that's ~5gb I think.

**Comment by jinfagang** [comment]
@prafullasd Thanks u for your help. Just wanna to see how this network works a small datasets would be enough for testing

**Comment by loretoparisi** [comment]
@prafullasd please provide pre-trained models.

**Comment by prafullasd** [comment]
@jinfagang Just uploaded a 5Gb version of CelebA to be default celeba-tfr.tar. Also updated readme to show how to generate the lsun dataset from the original images (which are smaller in size, eg: church_outdoor is 2.3GB)
