### ISSUE TITLE
When uploading an image to demo, there is net::ERR_CONNECTION_REFUSED

### ISSUE THREAD

**Issue by pauluskim** [openai/glow#64]
In server.py,
`if __name__ == '__main__': `                                                                     
`    print('Running Flask app...')`
`    app.run(host='0.0.0.0', port=8880,  debug=True)`

In glowDemo.js            
`const SERVER = "http://127.0.0.1:8880" // Change to wherver you have the server running`

When I curl in a terminal,
I also get the response from the server.

<img width="500"  src="https://user-images.githubusercontent.com/10319825/48002516-21c49f00-e14f-11e8-9fbf-5f80e03effff.png">

But when I request /api/align_encode by uploading an image in the demo page.
There is an ERR_CONNECTION_REFUSED.
<img width="763"  src="https://user-images.githubusercontent.com/10319825/48002624-6ea87580-e14f-11e8-9d1d-8ddd21faae7f.png">

Thank you for your help.

**Comment by anth2o** [comment]
Hi, did you manage to solve this issue ?
