### ISSUE TITLE
Demo: Privacy statement

### ISSUE THREAD

**Issue by renatobellotti** [openai/glow#93]
Dear people of OpenAI,

First: Thanks a lot for this cool piece of software!
I'm very keen about my privacy, so I'd like to retain control over my data.
At first, I thought the demo of glow was running in the browser and played around with a picture of myself, but then I've realised that the operations take place on your server.
Since I could neither find a privacy statement nor a contact form, I'm writing this issue to ask you whether the uploaded images are stored persistently on the server. If they are, how do you use them, and is there a way to delete them?

**Comment by prafullasd** [comment]
Hi Renato,

The images are not stored on the server. The server keeps no persistent / cached state either. Every request from the client has to send either the image or latents again. Fyi, the code for the server is here https://github.com/openai/glow/blob/master/demo/server.py

**Comment by renatobellotti** [comment]
Thanks for your fast answer, that's great news!
